In [13]:
import numpy as np

In [16]:
# 1. 使用 Numpy 创建一个包含 1 到 10 的整数的一维数组，并将其重塑为 2 行 5 列的二维数组。
# 提示：重塑方法 reshape(形状)
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array = array.reshape(2, 5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
# 2. 创建一个 3*4 的二维数组，并用 $[1, 5]$ 的随机整数进行填充
array = np.random.randint(1, 5, size=(3, 4))
print(array)

[[1 4 2 1]
 [1 3 2 2]
 [3 4 3 4]]


In [18]:
# 3. 取出上述创建数组的前两行和后三列 
array = array[:2, -3:]
print(array)

[[4 2 1]
 [3 2 2]]
